//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueTex {
            get {
                object obj = ResourceManager.GetObject("BlueTex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flueben {
            get {
                object obj = ResourceManager.GetObject("flueben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenTex {
            get {
                object obj = ResourceManager.GetObject("GreenTex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap holecut {
            get {
                object obj = ResourceManager.GetObject("holecut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap holefront {
            get {
                object obj = ResourceManager.GetObject("holefront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hp_bar_liv {
            get {
                object obj = ResourceManager.GetObject("hp_bar_liv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hpbar {
            get {
                object obj = ResourceManager.GetObject("hpbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kamera {
            get {
                object obj = ResourceManager.GetObject("kamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mole {
            get {
                object obj = ResourceManager.GetObject("mole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation1 {
            get {
                object obj = ResourceManager.GetObject("moleanimation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation10 {
            get {
                object obj = ResourceManager.GetObject("moleanimation10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation11 {
            get {
                object obj = ResourceManager.GetObject("moleanimation11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation12 {
            get {
                object obj = ResourceManager.GetObject("moleanimation12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation13 {
            get {
                object obj = ResourceManager.GetObject("moleanimation13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation14 {
            get {
                object obj = ResourceManager.GetObject("moleanimation14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation2 {
            get {
                object obj = ResourceManager.GetObject("moleanimation2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation3 {
            get {
                object obj = ResourceManager.GetObject("moleanimation3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation4 {
            get {
                object obj = ResourceManager.GetObject("moleanimation4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation5 {
            get {
                object obj = ResourceManager.GetObject("moleanimation5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation6 {
            get {
                object obj = ResourceManager.GetObject("moleanimation6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation7 {
            get {
                object obj = ResourceManager.GetObject("moleanimation7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation8 {
            get {
                object obj = ResourceManager.GetObject("moleanimation8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimation9 {
            get {
                object obj = ResourceManager.GetObject("moleanimation9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationattack1 {
            get {
                object obj = ResourceManager.GetObject("moleanimationattack1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationattack2 {
            get {
                object obj = ResourceManager.GetObject("moleanimationattack2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationattack3 {
            get {
                object obj = ResourceManager.GetObject("moleanimationattack3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationattack4 {
            get {
                object obj = ResourceManager.GetObject("moleanimationattack4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationattack5 {
            get {
                object obj = ResourceManager.GetObject("moleanimationattack5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue1 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue10 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue11 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue12 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue13 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue14 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue2 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue3 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue4 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue5 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue6 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue7 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue8 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationblue9 {
            get {
                object obj = ResourceManager.GetObject("moleanimationblue9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationdefeated {
            get {
                object obj = ResourceManager.GetObject("moleanimationdefeated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen1 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen10 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen11 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen12 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen13 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen14 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen2 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen3 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen4 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen5 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen6 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen7 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen8 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationgreen9 {
            get {
                object obj = ResourceManager.GetObject("moleanimationgreen9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred1 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred10 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred11 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred12 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred13 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred14 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred2 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred3 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred4 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred5 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred6 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred7 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred8 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationred9 {
            get {
                object obj = ResourceManager.GetObject("moleanimationred9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow1 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow10 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow11 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow12 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow13 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow14 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow2 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow3 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow4 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow5 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow6 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow7 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow8 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moleanimationyellow9 {
            get {
                object obj = ResourceManager.GetObject("moleanimationyellow9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap molecut {
            get {
                object obj = ResourceManager.GetObject("molecut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap molehole {
            get {
                object obj = ResourceManager.GetObject("molehole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap molimation {
            get {
                object obj = ResourceManager.GetObject("molimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic1 {
            get {
                object obj = ResourceManager.GetObject("Pic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic10 {
            get {
                object obj = ResourceManager.GetObject("Pic10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic11 {
            get {
                object obj = ResourceManager.GetObject("Pic11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic12 {
            get {
                object obj = ResourceManager.GetObject("Pic12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic13 {
            get {
                object obj = ResourceManager.GetObject("Pic13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic14 {
            get {
                object obj = ResourceManager.GetObject("Pic14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic15 {
            get {
                object obj = ResourceManager.GetObject("Pic15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic16 {
            get {
                object obj = ResourceManager.GetObject("Pic16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic17 {
            get {
                object obj = ResourceManager.GetObject("Pic17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic18 {
            get {
                object obj = ResourceManager.GetObject("Pic18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic2 {
            get {
                object obj = ResourceManager.GetObject("Pic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic3 {
            get {
                object obj = ResourceManager.GetObject("Pic3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic4 {
            get {
                object obj = ResourceManager.GetObject("Pic4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic5 {
            get {
                object obj = ResourceManager.GetObject("Pic5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic6 {
            get {
                object obj = ResourceManager.GetObject("Pic6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic7 {
            get {
                object obj = ResourceManager.GetObject("Pic7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic8 {
            get {
                object obj = ResourceManager.GetObject("Pic8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pic9 {
            get {
                object obj = ResourceManager.GetObject("Pic9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedTex {
            get {
                object obj = ResourceManager.GetObject("RedTex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transparentpng {
            get {
                object obj = ResourceManager.GetObject("transparentpng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unavngivet4 {
            get {
                object obj = ResourceManager.GetObject("Unavngivet4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowTex {
            get {
                object obj = ResourceManager.GetObject("YellowTex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
